project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Warwick Stats Resources"
  favicon: images/warwick-monogram-favicon.png
  navbar:
    right:
      - text: "Resources"
        file: resources.qmd
      - text: "Courses"
        file: courses.qmd
      - icon: github
        href: https://github.com/Warwick-Stats-Resources/
  page-footer: "Website, resources and courses developed by [Ella Kaye](https://warwick.ac.uk/ellakaye)" 
  
format:
  html:
    theme: custom.scss
    highlight-style: warwick.theme
    toc: true
    link-external-newwindow: true
    

