---
title: "Courses"
---

We teach three courses annually, usually one per term. 

## Upcoming/current courses

### R Foundations (Oct--Nov 2025)

[{{< fa globe >}} website](https://warwick-stats-resources.github.io/r-foundations-2025/){.btn .btn-primary}
[{{< fa brands github >}} source](https://github.com/Warwick-Stats-Resources/r-foundations-2025){.btn .btn-primary}
[{{< fa list >}} sign-up](https://warwick.ac.uk/ellakaye/r-foundations-2025){.btn .btn-primary}

This course is primarily aimed at first year Statistics PhD students. It has been developed as a prerequisite for those attending the [Academy for PhD Training in Statistics (APTS)](https://warwick.ac.uk/fac/sci/statistics/apts/) to cover the R material that’s required for those modules.

We cover an introduction to R and RStudio; Data types, structures, and data wrangling using the tidyverse; programming in R; simulation and optimisation; graphics (both base and ggplot2), and Quarto.

## Past courses

### R Foundations 

**Previous iterations**

- R Foundations (Oct--Nov 2025): [website](https://warwick-stats-resources.github.io/r-foundations-2024/), [source](https://github.com/Warwick-Stats-Resources/r-foundations-2024)

- R for Data Science (March 2024): [website](https://warwick-stats-resources.github.io/r-for-data-science-2024/), [source](https://github.com/Warwick-Stats-Resources/r-for-data-science-2024)

- R Foundations (October--December, 2023): [website](https://warwick-stats-resources.github.io/r-foundations/), s[source](https://github.com/Warwick-Stats-Resources/r-foundations)

### R Programming (March 24th-25th, 2025)

[{{< fa globe >}} website](https://warwick-stats-resources.github.io/r-programming-2025/){.btn .btn-primary}
[{{< fa brands github >}} source](https://github.com/Warwick-Stats-Resources/r-programming-2025){.btn .btn-primary}

This is an intermediate/advanced level course. Topics covered include writing functions, error handling and debugging, classes and methods, efficient programming, profiling, C++ and Rcpp, and R tools for working with git/GitHub.

**Previous iterations**

- R Programming (March 2024): [website](https://warwick-stats-resources.github.io/r-programming-2024/), [source](https://github.com/Warwick-Stats-Resources/r-programming-2024)

- Advanced R and R Packages (July 2023): [website](https://warwick-stats-resources.github.io/advanced-r-packages/), [source](https://github.com/Warwick-Stats-Resources/advanced-r-packages)


### R Package Development (June 2025)

[{{< fa globe >}} website](https://warwick-stats-resources.github.io/r-packages-2025/){.btn .btn-primary}
[{{< fa brands github >}} source](https://github.com/Warwick-Stats-Resources/r-packages-2025){.btn .btn-primary}

This is a hands-on workshop covering the entire process of creating an R package: including functions and data, checking and testing, all levels of documentation, publication and maintenance. The final session covers the advanced topic of using Rcpp code in a package.

**Previous iterations**

- R Packages (June 2024): [website](https://warwick-stats-resources.github.io/r-programming-2024/), [source](https://github.com/Warwick-Stats-Resources/r-programming-2024)

- Advanced R and R Packages (July 2023): [website](https://warwick-stats-resources.github.io/advanced-r-packages/), [source](https://github.com/Warwick-Stats-Resources/advanced-r-packages)